plugins {
    id 'java'
}

group = 'top.rymc'
version = '2.3.1'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {

    implementation 'io.netty:netty-common:4.2.3.Final'
    implementation 'io.netty:netty-handler:4.2.3.Final'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

}